# -*- coding: utf-8 -*-
# Game data for My Games Bay.
# Slugs and URLs are unchanged from the original index.html.
# How-to-play / controls text was written from what each live game page shows
# on its own start screen (fetched during the audit). Fields marked verified=False
# could not be read from the game (canvas-only UI) and need owner input.

GAMES = [
 dict(slug="tamil-city", title="Tamil City", icon="🏙️", cat="Action",
  ingame="Tamil Nagaram (தமிழ் நகரம்)", url="https://tamil-city-web-game.vercel.app/",
  short="Explore an open-world Tamil city: talk to locals, take quests, run shops and play mini-games.",
  about="Tamil City is an open-world city-life game. You walk or drive an auto-rickshaw through districts such as a temple area, market, beach and harbor, talk to townsfolk, accept quests and earn coins. Menus are mostly in Tamil, with English help text in the Help panel.",
  how=["Choose New Game to start fresh, or Continue to load your saved progress.",
       "Walk around the city and talk to people to discover quests. Open the Quests panel to track them.",
       "Earn coins from quests, trading and mini-games, then spend them in shops or on gifts for friends.",
       "Open Pause and choose the save option to store progress. The game also autosaves periodically."],
  controls=[("Move","WASD or Arrow keys / on-screen joystick"),("Sprint","Hold Shift"),("Interact","E / round action button"),
            ("Menus","I inventory, Q quests, M map, Esc pause")],
  objective="Complete quest lines, build friendships, earn money and unlock every achievement in the city.",
  features=["14 townsfolk with schedules and dialogue","13 quest lines and 20+ achievements","8 shops with buying and selling","6 mini-games including fishing, cooking and traffic dodging","Day and night cycle with weather","Save system and fast travel"],
  mobile="Yes. A joystick and action button appear on touch screens.", verified=True),

 dict(slug="cockroach-man", title="Cockroach Man", icon="🪳", cat="Action",
  ingame="Cockroach Man: Immersive Cyber Arcade", url="https://cockroach-man.vercel.app/",
  short="A cyber-styled arcade game starring a cockroach.",
  about="Cockroach Man is a cyber-themed arcade game drawn entirely on a canvas, so its instructions appear only inside the game.",
  how=["Open the game and follow the prompts on its start screen."],
  controls=[("Controls","Shown in the game's start screen")],
  objective="Follow the goal shown in the game.",
  features=["Cyber arcade visual style","Plays in the browser with no install"],
  mobile="Designed for mobile browsers (uses a mobile viewport).", verified=False),

 dict(slug="chameleon", title="Chameleon", icon="🦎", cat="Puzzle",
  ingame="Meccha Chameleon: Color-Match Survival", url="https://meccha-chameleon-wheat.vercel.app/",
  short="Match your color to incoming barriers and survive as the speed climbs.",
  about="A fast color-matching survival game. Colored barriers slide toward your chameleon, and you must switch to the matching color before each one arrives. The game speeds up as your score grows.",
  how=["Press Start Game.","Watch the color of the next barrier.","Switch your chameleon to the same color before the barrier reaches you.","Keep going as the speed multiplier rises. A wrong color ends the run."],
  controls=[("Desktop","Arrow keys or number keys 1 to 4"),("Mobile","Tap the color buttons")],
  objective="Get the highest score you can. The game keeps your best score for the session.",
  features=["Four colors to switch between","Speed multiplier that increases over time","Score and best-score display"],
  mobile="Yes, with tap color buttons.", verified=True),

 dict(slug="cockroach-dash", title="Cockroach Dash", icon="🏃", cat="Arcade",
  ingame="Cockroach Man (kitchen survival)", url="https://cockroach-dash.vercel.app/",
  short="Scurry across a kitchen floor, collect crumbs and dodge whatever wants to squash you.",
  about="An arcade game set in a kitchen. You move a cockroach left and right, dash to safety and collect as many crumbs as you can before you get squished.",
  how=["Press Start Game.","Move left and right to collect crumbs.","Use the dash to escape danger.","When you are squished, the game shows how many crumbs you collected. Press Try Again to go again."],
  controls=[("Desktop","Left/Right arrows or A/D to move, Space to dash"),("Mobile","On-screen left and right arrows")],
  objective="Collect as many crumbs as possible without getting squished.",
  features=["Crumb counter","Dash move for close calls","Quick restart after each run"],
  mobile="Yes, with on-screen arrow buttons.", verified=True),

 dict(slug="queen-bee-kitchen", title="Queen Bee Kitchen", icon="🐝", cat="Puzzle",
  ingame="Queen Bee Kitchen", url="https://queen-bee-kitchen-game.vercel.app/",
  short="Pick an order, tap its ingredients in the right sequence and keep your combo alive.",
  about="A tap-based cooking puzzle. Customer orders appear as cards. You select one and tap its ingredients in order at the Chef's Station. Orders expire, so speed and accuracy both matter.",
  how=["Tap an order card to select it.","Tap the highlighted ingredients in the correct order.","Finish dishes quickly to build combo bonuses.","Do not let orders expire or your combo resets."],
  controls=[("Mouse or touch","Click or tap order cards and ingredients")],
  objective="Complete orders to earn points, clear each level and beat your best combo.",
  features=["Multiple levels","Combo bonuses","Game-over summary with score, level reached and best combo"],
  mobile="Yes. Built for tapping.", verified=True),

 dict(slug="queen-bee-kitchen-model", title="Queen Bee Kitchen Model", icon="🍳", cat="Puzzle",
  ingame="Queen Bee Kitchen: Recipe Rush", url="https://queen-bee-kitchen-game-model.vercel.app/",
  short="A 60-second recipe rush: tap the ingredients the Queen Bee needs before time runs out.",
  about="Recipe Rush is a timed cooking game with a 60-second clock. The Queen Bee shows the recipe she needs and you tap matching ingredients. It is a separate, shorter game from Queen Bee Kitchen.",
  how=["Press Start Cooking.","Read the recipe and tap each ingredient it needs.","Complete recipes to build a streak.","When the 60 seconds are up, the game shows recipes completed and your streak."],
  controls=[("Mouse or touch","Click or tap ingredients")],
  objective="Complete as many recipes as possible in 60 seconds.",
  features=["60-second timer","Recipe counter and streak counter","One-tap restart"],
  mobile="Yes. Built for tapping.", verified=True, dup=True,
  note="This is a shorter, timed version of Queen Bee Kitchen with the same tap-the-ingredients idea, so it is kept playable but not promoted in search."),

 dict(slug="kullanari-run", title="Kullanari Run", icon="🦊", cat="Action",
  ingame="Kullanari Runner: The Endless Village Runner", url="https://kullanari-run.vercel.app/",
  short="Jump over obstacles in an endless village run and chase your high score.",
  about="An endless runner set in a village. Your character runs automatically and you time your jumps to clear obstacles. The score and your high score are shown at the top.",
  how=["Tap or press Space to start.","Jump over each obstacle as it arrives.","When you crash, tap or press Space to restart."],
  controls=[("Desktop","Space or Up arrow to jump"),("Mobile","Tap the screen to jump")],
  objective="Run as far as you can and beat your high score.",
  features=["Endless gameplay","Score and high score","One-button controls"],
  mobile="Yes. One tap to jump.", verified=True),

 dict(slug="neon-dodge", title="Neon Dodge", icon="⚡", cat="Arcade",
  ingame="Neon Dodge", url="https://neon-dodge-five.vercel.app/",
  short="Steer through a field of red blocks and grab gold stars for points.",
  about="A reflex arcade game. Red blocks fall or drift across the screen and you move your player out of the way while collecting gold stars.",
  how=["Press Start Game.","Move to avoid the red blocks.","Touch gold stars to score.","Your best score is shown next to the current score."],
  controls=[("Desktop","Mouse or Arrow keys"),("Mobile","Drag with your finger")],
  objective="Survive as long as possible and collect stars.",
  features=["Mouse, touch and keyboard support","Score and best score"],
  mobile="Yes.", verified=True),

 dict(slug="neon-arena", title="Neon Arena P2P", icon="🌈", cat="Multiplayer",
  ingame="Neon Arena P2P: Online Multiplayer", url="https://neon-arena-p2p.vercel.app/",
  short="A peer-to-peer shooter arena. Host a room, join a friend's room, or play locally across tabs.",
  about="An arena shooter that connects players directly (peer-to-peer). There is no public matchmaking: one player hosts and shares a room code, and the other pastes it to join. A local mode lets you test across two browser tabs on one computer.",
  how=["Choose Host Game and press Create Room, then send the room code to a friend.","Your friend chooses Join Game, pastes the code, and sends back an answer code.","Paste the answer code into Finalize Connection to start.","Or choose Local Multiplayer to play across browser tabs on the same computer."],
  controls=[("Fire","FIRE button on screen"),("Other controls","Shown in the game on your device")],
  objective="Score more kills than your opponent and avoid elimination. You respawn after being eliminated.",
  features=["Host, join and local play modes","HP, weapon and kill/death display","Connection speed (ping) indicator"],
  mobile="Touch controls are included.", verified=True,
  note="You need a second person to play online. There are no computer opponents or public lobbies."),

 dict(slug="boxing", title="1v1 Boxing", icon="🥊", cat="Multiplayer",
  ingame="CORNERMEN: Boxing", url="https://1v1-boxing.vercel.app/",
  short="A side-view boxing duel: move, dodge and punch your way through best of three rounds.",
  about="CORNERMEN is a side-on boxing game played in rounds. You and your rival trade punches, and you win by reading the wind-up and dodging or jumping the shot. Rounds are timed and a match is best of three.",
  how=["Press Touch Gloves to begin.","Work your footwork to close the distance.","Punch when you are in range, and dodge or jump when your rival winds up.","Win two rounds to win the match."],
  controls=[("Move","A and D / on-screen arrows"),("Jump","W / Jump button"),("Dodge","S / Dodge button"),("Punch","Space / Punch button")],
  objective="Win the best-of-three match.",
  features=["Timed rounds","Combo counter","Jump and dodge moves"],
  mobile="Yes, but the game asks you to rotate your phone to landscape.", verified=True),

 dict(slug="chess", title="Chess Dun", icon="♟️", cat="Strategy",
  ingame="Match Point: Online Chess", url="https://chess-dun-one.vercel.app/",
  short="Classic chess for two players: share one device, or connect online with a room code.",
  about="A standard chess board with three ways to play: Pass and Play on one device, or Host and Join an online room using a numeric code. There is no computer opponent, so you need a second person.",
  how=["Choose Pass and Play to share one device, or Host Game to get a room code.","To play online, send your code to your opponent. They choose Join Game and enter it.","The host plays White and the guest plays Black.","Tap a piece, then tap its destination square."],
  controls=[("Mouse or touch","Click or tap a piece, then its destination"),("Buttons","New Game, Undo, Flip Board, Resign")],
  objective="Checkmate your opponent's king.",
  features=["Pass and Play and online rooms","Undo, flip board and resign","Move list and captured pieces"],
  mobile="Yes. Works on phones and tablets.", verified=True,
  note="You need a second player. There is no computer opponent."),

 dict(slug="gravity-loop", title="Gravity Loop", icon="🌀", cat="Puzzle",
  ingame="Neon Orbit", url="https://gravity-loop.vercel.app/",
  short="Flip your orbit direction to dodge red asteroids and collect gold stars.",
  about="A one-button reflex game. Your ship circles an orbit and you switch its direction at the right moment to avoid asteroids and reach stars.",
  how=["Press Play.","Tap, click or press Space to reverse your orbit direction.","Avoid red asteroids and touch gold stars.","When you crash, press Try Again."],
  controls=[("Desktop","Click or Space"),("Mobile","Tap")],
  objective="Collect stars, avoid asteroids and beat your best score.",
  features=["One-button control","Score and best score"],
  mobile="Yes. One tap to switch direction.", verified=True),

 dict(slug="click-me", title="Click Me", icon="🖱️", cat="Arcade",
  ingame="Click Me: Asymmetric Hell", url="https://click-me-mocha.vercel.app/",
  short="A tricky click challenge with three lives. Easier with a mouse than on a phone.",
  about="A pointer-skill game with a score, a best score and three lives. Its start screen warns that it is fair but tricky on a computer and much harder on a phone.",
  how=["Press Start.","Follow what appears on screen and click or tap accurately.","You lose a life on a mistake. The run ends when your three lives are gone."],
  controls=[("Desktop","Mouse"),("Mobile","Tap")],
  objective="Score as high as you can before losing all three lives.",
  features=["Score and best score","Three lives"],
  mobile="Works on mobile, but the game itself warns that it is harder on touch screens.", verified=True),

 dict(slug="phaseshift", title="PhaseShift", icon="⚡", cat="Action",
  ingame="Phase Shift: Dimension Survival", url="https://phaseshift-game.vercel.app/",
  short="Shift between two dimensions. Crimson hazards hurt in one, cyan hazards in the other.",
  about="A one-button survival game. You exist in two phases at once: crimson obstacles are dangerous only in Phase A, and cyan obstacles only in Phase B. You shift phase to pass through whichever color is harmless.",
  how=["Press Enter the Rift.","Tap, click or press Space to shift phase.","Pass through obstacles of the color that cannot hurt you in your current phase.","Survive as long as you can."],
  controls=[("Desktop","Click or Space"),("Mobile","Tap anywhere")],
  objective="Survive as long as possible and set a new high score.",
  features=["Two-phase mechanic","Score and best score"],
  mobile="Yes. Tap anywhere.", verified=True),

 dict(slug="echotrace", title="EchoTrace", icon="🔊", cat="Puzzle",
  ingame="Echo Trace: Temporal Dodge", url="https://echotrace-game.vercel.app/",
  short="Swap places with your fading echo from 1.5 seconds ago to escape approaching walls.",
  about="You leave a fading echo everywhere you move. When walls close in, you swap with your echo and jump back in time to where you were, which can be a safe spot.",
  how=["Press Begin.","Move with touch or mouse.","When a wall is about to hit you, tap the Swap button or press Space to teleport to your echo.","Survive as long as you can."],
  controls=[("Desktop","Mouse to move, Space to swap"),("Mobile","Drag to move, tap the Swap button")],
  objective="Survive and beat your best score.",
  features=["Echo timer display","Score and best score"],
  mobile="Yes.", verified=True),

 dict(slug="tidal", title="Tidal", icon="🌊", cat="Arcade",
  ingame="TIDAL: Control the Ocean", url="https://tidal-game.vercel.app/",
  short="You control the tide, not the submarine. Raise and lower the ocean to dive safely.",
  about="An unusual arcade game: a submarine moves automatically and you control the water level around it. Raise the tide to submerge rocks, lower it to avoid floating mines, and collect pearls as you go deeper.",
  how=["Press Dive.","Drag up or down anywhere on the screen to raise or lower the tide.","Raise the tide to cover rocks and lower it to avoid mines.","Collect pearls and go as deep as you can. Smooth movements are safer."],
  controls=[("Desktop","Click and drag up or down"),("Mobile","Touch and drag up or down")],
  objective="Reach the greatest depth and collect pearls.",
  features=["Depth, pearls and best-depth counters"],
  mobile="Yes.", verified=True),

 dict(slug="kitchen-order", title="Kitchen Order", icon="🍳", cat="Puzzle",
  ingame="Queen Bee's Kitchen: Order Up!", url="https://kitchen-order-iota.vercel.app/",
  short="Run the Queen's honeycomb kitchen: tap ingredients to fill several tables' orders at once.",
  about="A multi-table order game. Several customers wait at once, each with a patience timer, and you tap the right ingredients to fill each order. Serving quickly and juggling tables earns combo boosts. The difference from Queen Bee Kitchen is that there you select one order card at a time, while here several tables wait at the same time.",
  how=["Press Open Kitchen.","Tap the ingredients each customer's order needs.","Serve before their patience runs out.","Use Pause to stop the game or quit to the menu."],
  controls=[("Mouse or touch","Click or tap ingredients"),("Buttons","Pause and sound toggle")],
  objective="Serve as many customers as possible and reach a high score.",
  features=["Levels and combo boost","Pause menu and sound toggle","Score, best and served counters"],
  mobile="Yes. Built for tapping.", verified=True),

 dict(slug="bee-collection", title="Bee Collection", icon="🐝", cat="Arcade",
  ingame="Queen Bee's Kitchen (catching game)", url="https://bee-collection-theta.vercel.app/",
  short="Fly the Queen through the hive kitchen, catch recipe ingredients and dodge pests.",
  about="A catching game. The Queen Bee flies around the kitchen. Each level gives a recipe (for example Blossom Tea) and you catch the ingredients it needs while avoiding pests.",
  how=["Press Start Cooking.","Steer the Queen to catch the ingredients in your recipe.","Avoid the pests.","Your recipe progress is shown as a counter (for example 0 / 6) next to the level number."],
  controls=[("Controls","Shown when you start the game")],
  objective="Complete each recipe and build your score.",
  features=["Recipe progress counter","Level counter","Pause menu and sound toggle"],
  mobile="Yes, with touch support.", verified=True),

 dict(slug="race-predictor", title="Neon Ride", icon="🏁", cat="Arcade",
  ingame="Neon Ride: Highway Rush (Neon Bike Race)", url="https://race-predictor-game-g8a2.vercel.app/",
  short="Steer a neon bike along a highway and avoid crashing as your speed rises.",
  about="A lane-dodging bike game. You steer left and right on a highway while your speed increases. The run ends when you crash.",
  how=["Press Start Engine.","Steer left and right to avoid obstacles.","Your score and speed are shown at the top.","When you crash, press Ride Again."],
  controls=[("Desktop","Left and Right arrow keys"),("Mobile","Tap the left or right side of the screen")],
  objective="Survive as long as possible for a high score.",
  features=["Speed counter","Score and best score"],
  mobile="Yes.", verified=True,
  note="This page was previously listed as 'Race Predictor', but the game is a bike dodging game, so it has been renamed. The URL is unchanged."),

 dict(slug="race-predictor-alt", title="Race Predictor", icon="🏎️", cat="Strategy",
  ingame="Race Predictor: Car Race Prediction Game", url="https://race-predictor-game.vercel.app/",
  short="Watch the red car and predict whether it will overtake or fall back. Points and lives only.",
  about="A prediction game. You watch a live race track and decide whether the red car will overtake or fall back. Three difficulty levels are available. The game uses points, streaks and lives only. There is no money or betting.",
  how=["Pick Easy, Medium or Hard.","Watch the red car on the live track.","Press Overtake or Fall Back to make your prediction.","A wrong prediction costs a life. The game ends when all three lives are gone."],
  controls=[("Mouse or touch","Click or tap the Overtake / Fall Back buttons")],
  objective="Build the longest streak and highest score.",
  features=["Easy, Medium and Hard modes","Score, streak, lives and best score"],
  mobile="Yes.", verified=True)
]

CATEGORIES = {
 "Action": "Action games test your reflexes and timing: run, jump, fight and explore.",
 "Arcade": "Arcade games are quick, score-based runs that are easy to pick up and hard to master.",
 "Puzzle": "Puzzle games reward quick thinking: match colors, follow recipes and plan your moves.",
 "Multiplayer": "Multiplayer games are played against another person, either online or on one device.",
 "Strategy": "Strategy games are about planning ahead, from chess to prediction challenges.",
}
COLORS = {
 "Action":("#ff4757","#ff9a1f"),"Arcade":("#39ff9d","#e9ff5c"),"Puzzle":("#3d8bff","#b06bff"),
 "Multiplayer":("#00f0ff","#ff2ee6"),"Strategy":("#ffd166","#9d5cff"),
}
